name = "hugo-minimal"
license = "MIT"
licenselink = "https://github.com/samuelmcpherson/hugo-minimal/blob/master/LICENSE.md"
description = "Minimal Hugo theme to develop from. Forked from hugo-xmin by Yihui"
homepage = "https://github.com/samuelmcpherson/hugo-minimal"
tags = ["minimal", "clean", "simple", "starter", "minimalist"]
min_version = "0.18"

[author]
  name = "Samuel McPherson-Gorham"
  homepage = "https://samuelmcpherson.net"
